fix

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -33,27 +33,42 @@ jobs:
     if: github.ref == 'refs/heads/master'
     
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: '10.0'
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v4
+      with:
+        dotnet-version: '10.0'
+      
+    - name: Build Project
+      run: |
+        dotnet restore
+          otnet build --configuration Release
 
-      - name: Install DocFX tool
-        run: dotnet tool install -g docfx
-
-      - name: DocFX metadata
-        run: docfx metadata
-        
-      - name: DocFX build
-        run: docfx build
-
-      - name: Create .nojekyll file
-        run: touch _site/.nojekyll
-
-      - name: Clean old pages artifact (on re-run)
+    - name: Install DocFX tool
+      run: dotnet tool install -g docfx
+      
+    - name: Run DocFX Build
+      run: docfx
+      
+      - name: Prepare Static Site Directory
+        run: |
+          mkdir -ント public-site || true
+          
+          BUILD_DIR=$(find . -name "index.html" ! -path "./public-site/*" ! -path "*/obj/*" ! -path "*/bin/*" | head -n 1 | xargs dirname)
+          
+          if [ -z "$BUILD_DIR" ]; then
+            echo "Error: DocFX not created index.html."
+            exit 1
+          fi
+          
+          echo "found in:  $BUILD_DIR"
+          cp -R $BUILD_DIR/* ./public-site/
+          
+          touch ./public-site/.nojekyll
+      
+      - name: Clean old pages artifact
         uses: geekyeggo/delete-artifact@v5
         with:
           name: github-pages
@@ -62,7 +77,7 @@ jobs:
       - name: Upload Pages Artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: _site
+          path: public-site
 
       - name: Deploy to GitHub Pages
         id: deployment
